# Generated by Django 5.1.6 on 2025-02-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_present_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
