# Generated by Django 5.1.7 on 2025-03-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_stock_updated_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='present_quantity',
        ),
    ]
